export const LOADING = 'LOADING'

export const BAR_CHART_DETAILS_SUCCESS= 'BAR_CHART_DETAILS_SUCCESS';
export const BAR_CHART_DETAILS_FAILURE= 'BAR_CHART_DETAILS_FAILURE';

export const LINE_CHART_DEATILS_SUCCESS = 'LINE_CHART_DEATILS_SUCCESS';
export const LINE_CHART_DEATILS_FAILURE = 'LINE_CHART_DEATILS_FAILURE';

export const SELECTED_CURRENCY_SUCCESS='SELECTED_CURRENCY_SUCCESS';
export const SELECTED_CURRENCY_FAILURE='SELECTED_CURRENCY_FAILURE';

export const CURRENCY_LIST_SUCCESS = 'CURRENCY_LIST_SUCCESS';
export const CURRENCY_LIST_FAILURE = 'CURRENCY_LIST_FAILURE';

